### ISSUE TITLE
On startup error

### ISSUE THREAD

**Issue by 7tech7** [bitfocus/companion-module-techministry-midirelay#20]
Here's a messa i kept getting

Unhandled Error
Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at Server.listen (node:net:1469:7)
    at Function.start (C:/Users/Cam/AppData/Local/Programs/midi-relay/resources/app.asar/api.js:136:15)
    at C:/Users/Cam/AppData/Local/Programs/midi-relay/resources/app.asar/index.js:145:6

**Comment by josephdadams** [comment]
This looks like an error with midi-relay, not the companion module. 

That error says port 4000 is already in use. Either by another instance or midi-relay or some other program.
